version: "3.9"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
