name: SvelteKit CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build
      run: npm run build
      working-directory: ./frontend

    - name: Run unit tests
      run: npm run test:unit
      working-directory: ./frontend

    - name: Run linter
      run: npm run lint
      working-directory: ./frontend

    - name: Check for security vulnerabilities
      run: npm audit
      working-directory: ./frontend
